version: "3.7"
# define all services
services:
  postgresql:
    image: "postgres:stools"
    restart: "no"
    container_name: postgres_stools
    ports:
      - "5432:5432"
    privileged: "true"
    build:
      context: ./
      dockerfile: dockerfile/postgres
    environment:
      - POSTGRES_PASSWORD=Ab123456a@
      - POSTGRES_USER=ssv
      - POSTGRES_DB=stools
      - POSTGRES_HOST_AUTH_METHOD=md5

  httpd:
    image: "httpd:stools"
    restart: "no"
    container_name: httpd_stools
    ports:
      - "8080:80"
    privileged: "true"
    build:
      context: ./
      dockerfile: dockerfile/httpd
    volumes:
      - "./data/source:/var/www/html"
    command: >
      bash -c "sh /tmp/composer.sh && apachectl -k start -DFOREGROUND"
